days_back: 14
collaborators:
  - name: Ryan Hodgson
    openalex_author_id: https://openalex.org/A5080425877
  - name: Steven A. Robinson
    openalex_author_id: https://openalex.org/A5125391470
  - name: Amélie Boutin
    openalex_author_id: https://openalex.org/A5104297431
  - name: Felix K. Chan
    openalex_author_id: https://openalex.org/A5125396149
  - name: Rachel T. Buxton
    openalex_author_id: https://openalex.org/A5125418520
  - name: Dalal E. L. Hanna
    openalex_author_id: https://openalex.org/A5125400806
  - name: J. Harry Caufield
    openalex_author_id: https://openalex.org/A5125692604
  - name: Joseph R. Bennett
    openalex_author_id: https://openalex.org/A5125431405
  - name: Joseph R. Bennett
    openalex_author_id: https://openalex.org/A5125764464
  - name: Stephen D. Murphy
    openalex_author_id: https://openalex.org/A5016767583
  - name: William J. Sutherland
    openalex_author_id: https://openalex.org/A5077493578
