bookstack:
  url: https://wiki.lab.tim-a.ca
  token_id: replace-me
  token_secret: replace-me
  book_id: 3
  chapter_id:
matrix:
  summary_file: matrix_digest.txt
podcast:
  script_file: podcast_script.md
