#!/usr/bin/env python3
"""Post the daily Mastodon toots generated by the digest pipeline.

Reads the 5 toots from daily_digest.json and posts them to Mastodon
one at a time. Skips posting if today's toots have already been sent
(safe to re-run without double-posting).

Required environment variables:
  MASTODON_INSTANCE_URL   e.g. https://mastodon.social or your own instance
  MASTODON_ACCESS_TOKEN   from Settings → Development → New Application

Optional:
  MASTODON_POST_DELAY_SEC seconds to wait between toots (default: 30)
  MASTODON_VISIBILITY     public | unlisted | private (default: public)
"""

from __future__ import annotations

import datetime
import os
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from common.io_utils import OUTPUT_DIR, STATE_DIR, dump_json, ensure_data_dirs, load_json
from common.runtime import is_test_mode

try:
    import requests
except ImportError:
    raise SystemExit("requests is required: pip install requests")


STATE_PATH = STATE_DIR / "mastodon_posted.json"


def already_posted_today(today: str) -> bool:
    state = load_json(STATE_PATH, default={})
    return state.get("posted_date") == today


def mark_posted(today: str, toots: list[str], post_ids: list[str]) -> None:
    dump_json(
        STATE_PATH,
        {
            "posted_date": today,
            "toot_count": len(toots),
            "post_ids": post_ids,
            "toots": toots,
        },
    )


def post_toot(instance_url: str, token: str, text: str, visibility: str) -> str:
    """Post a single toot and return its post ID."""
    url = f"{instance_url.rstrip('/')}/api/v1/statuses"
    resp = requests.post(
        url,
        headers={"Authorization": f"Bearer {token}"},
        json={"status": text, "visibility": visibility},
        timeout=30,
    )
    resp.raise_for_status()
    return resp.json().get("id", "")


def main() -> None:
    ensure_data_dirs()

    instance_url = os.getenv("MASTODON_INSTANCE_URL", "").strip()
    token = os.getenv("MASTODON_ACCESS_TOKEN", "").strip()
    delay = int(os.getenv("MASTODON_POST_DELAY_SEC", "30"))
    visibility = os.getenv("MASTODON_VISIBILITY", "public").strip()

    if not instance_url or not token:
        raise SystemExit(
            "MASTODON_INSTANCE_URL and MASTODON_ACCESS_TOKEN must be set.\n"
            "Get a token from: your-instance/settings/applications"
        )

    digest = load_json(OUTPUT_DIR / "daily_digest.json", default={})
    if not digest:
        raise SystemExit("No daily_digest.json found. Run the pipeline first.")

    toots: list[str] = digest.get("mastodon_toots", [])
    if not toots:
        print("No Mastodon toots in digest — nothing to post.")
        return

    today = digest.get("date", datetime.date.today().isoformat())

    if already_posted_today(today):
        print(f"Toots for {today} already posted — skipping.")
        return

    if is_test_mode():
        print(f"[test mode] Would post {len(toots)} toots to {instance_url}:")
        for i, toot in enumerate(toots, 1):
            print(f"\n  Toot {i}:\n  {toot}")
        return

    post_ids: list[str] = []
    for i, toot in enumerate(toots, 1):
        print(f"Posting toot {i}/{len(toots)}...")
        try:
            post_id = post_toot(instance_url, token, toot, visibility)
            post_ids.append(post_id)
            print(f"  Posted: {instance_url}/@junkyard_racoon/{post_id}")
        except Exception as exc:
            print(f"  Warning: toot {i} failed — {exc}", file=sys.stderr)
            post_ids.append("")
        if i < len(toots):
            time.sleep(delay)

    mark_posted(today, toots, post_ids)
    posted = sum(1 for p in post_ids if p)
    print(f"Done: {posted}/{len(toots)} toots posted for {today}.")


if __name__ == "__main__":
    main()
